//! Auto-generated tankopedia, to update run `blitz-tanks bundle-tankopedia`.

use phf::{phf_map, Map};

use crate::models::{Vehicle, VehicleType};

pub static TANKOPEDIA: Map<u16, Vehicle> = phf_map! {
    81_u16 => Vehicle {
        tank_id: 81,
        name: "Vickers Medium Mk. I",
        tier: 1,
        type_: VehicleType::Medium,
        is_premium: false,
        is_collectible: false,
        image_url: "https://glossary-eu-static.gcdn.co/icons/wotb/10.0.0.366/uploaded/vehicles/hd/GB01_Medium_Mark_I.png",
        image_content: Some(include_bytes!("vendored/81.webp")),
    },
    2049_u16 => Vehicle {
        tank_id: 2049,
        name: "A-20",
        tier: 4,
        type_: VehicleType::Light,
        is_premium: false,
        is_collectible: false,
        image_url: "https://glossary-eu-static.gcdn.co/icons/wotb/10.0.0.366/uploaded/vehicles/hd/A-20.png",
        image_content: Some(include_bytes!("vendored/2049.webp")),
    },
    2145_u16 => Vehicle {
        tank_id: 2145,
        name: "Type 97 Chi-Ha",
        tier: 3,
        type_: VehicleType::Medium,
        is_premium: false,
        is_collectible: false,
        image_url: "https://glossary-eu-static.gcdn.co/icons/wotb/10.0.0.366/uploaded/vehicles/hd/Chi_Ha.png",
        image_content: Some(include_bytes!("vendored/2145.webp")),
    },
    5761_u16 => Vehicle {
        tank_id: 5761,
        name: "Škoda T 50",
        tier: 9,
        type_: VehicleType::Medium,
        is_premium: false,
        is_collectible: false,
        image_url: "https://glossary-eu-static.gcdn.co/icons/wotb/10.0.0.366/uploaded/vehicles/hd/Cz02_T50.png",
        image_content: Some(include_bytes!("vendored/5761.webp")),
    },
    5953_u16 => Vehicle {
        tank_id: 5953,
        name: "AMX 38",
        tier: 2,
        type_: VehicleType::Medium,
        is_premium: false,
        is_collectible: false,
        image_url: "https://glossary-eu-static.gcdn.co/icons/wotb/10.0.0.366/uploaded/vehicles/hd/AMX38.png",
        image_content: Some(include_bytes!("vendored/5953.webp")),
    },
    6449_u16 => Vehicle {
        tank_id: 6449,
        name: "WZ-113G FT",
        tier: 10,
        type_: VehicleType::AntiTank,
        is_premium: false,
        is_collectible: false,
        image_url: "https://glossary-eu-static.gcdn.co/icons/wotb/10.0.0.366/uploaded/vehicles/hd/CH38_WZ113G-FT.png",
        image_content: Some(include_bytes!("vendored/6449.webp")),
    },
    26145_u16 => Vehicle {
        tank_id: 26145,
        name: "High Score",
        tier: 5,
        type_: VehicleType::Medium,
        is_premium: true,
        is_collectible: true,
        image_url: "https://glossary-eu-static.gcdn.co/icons/wotb/10.0.0.366/uploaded/vehicles/hd/A05_M4_105BD.png",
        image_content: Some(include_bytes!("vendored/26145.webp")),
    },
    52241_u16 => Vehicle {
        tank_id: 52241,
        name: "Pz.Kpfw. B2 740 (f)",
        tier: 4,
        type_: VehicleType::Heavy,
        is_premium: true,
        is_collectible: true,
        image_url: "https://glossary-eu-static.gcdn.co/icons/wotb/10.0.0.366/uploaded/vehicles/hd/B-1bis_captured.png",
        image_content: Some(include_bytes!("vendored/52241.webp")),
    },
    63601_u16 => Vehicle {
        tank_id: 63601,
        name: "Dracula",
        tier: 7,
        type_: VehicleType::Medium,
        is_premium: true,
        is_collectible: false,
        image_url: "https://glossary-eu-static.gcdn.co/icons/wotb/10.0.0.366/uploaded/vehicles/hd/AMX_dracula.png",
        image_content: Some(include_bytes!("vendored/63601.webp")),
    },
};
